server:
  port: 9002
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.10.55:3306/oauth2-simple
    username: root
    password: base@GO5r1Ydsb6H
    type: com.alibaba.druid.pool.DruidDataSource
  main:
    allow-bean-definition-overriding: true #允许我们自己覆盖spring放入到IOC容器的对象
mybatis:
  type-aliases-package: com.oauth2.domain
  mapper-locations: classpath:mapper/*.xml
logging:
  level:
    com.oauth2: debug